In [1]:
import numpy as np
import pandas as pd

In [2]:
a = pd.Series([10,20,30])
print(a)

0    10
1    20
2    30
dtype: int64


In [3]:
a = pd.Series([10,20,30], index=[1,2,3])
print(a)

1    10
2    20
3    30
dtype: int64


In [4]:
a = pd.Series([10,20,30], index=['a','b','c'])
print(a)

a    10
b    20
c    30
dtype: int64


In [5]:
a = pd.Series([10,20,np.nan])
print(a)

0    10.0
1    20.0
2     NaN
dtype: float64


In [6]:
a = [10,20,30,"new"]
print(a)
type(a)

[10, 20, 30, 'new']


list

In [7]:
a = [10,20,30,"new"]
print(a)
type(a)
b= pd.Series(a)
print(b)
type(b)

[10, 20, 30, 'new']
0     10
1     20
2     30
3    new
dtype: object


pandas.core.series.Series

In [8]:
a = [10,20,30,40]
df= pd.DataFrame(a)
print(df)
type(df)

    0
0  10
1  20
2  30
3  40


pandas.core.frame.DataFrame

In [9]:
a = ['New',20],['old',10]
print(a)

(['New', 20], ['old', 10])


In [10]:
a = ['New',20],['old',10]
print(a)
df= pd.DataFrame(a)
print(df)

(['New', 20], ['old', 10])
     0   1
0  New  20
1  old  10


In [11]:
a = ['New',20],['old',10]
print(a)
df= pd.DataFrame(a, columns=['Type','No'])
print(df['Type'])

(['New', 20], ['old', 10])
0    New
1    old
Name: Type, dtype: object


In [13]:
x = df['Type']
type(x)

pandas.core.series.Series

In [14]:
x = df[['Type']]
type(x)

pandas.core.frame.DataFrame

In [19]:
a = {'Name' :['Jan','Kot'],'Age': [35,40]}
print(a)

{'Name': ['Jan', 'Kot'], 'Age': [35, 40]}


In [21]:
df= pd.DataFrame(a)
print(df)

  Name  Age
0  Jan   35
1  Kot   40


In [22]:
a= np.array([[1,2],[2,3]])
print(a)

[[1 2]
 [2 3]]


In [25]:
a= np.array([[1,2],[2,3]])
print(a)
b= pd.DataFrame(a)
print(b)
c= np.array(b)
print(c)

[[1 2]
 [2 3]]
   0  1
0  1  2
1  2  3
[[1 2]
 [2 3]]
